version: '2.4'
volumes:
  lumeo-container-name: {}
services:
  gpu:
    build:
      context: ./gpu
    privileged: true
  lumeo:
    build:
      context: ./lumeo
    restart: unless-stopped
    volumes:
      - 'lumeo-container-name:/var/lib/lumeo'
    environment:
      LUMEO_APP_ID: <your lumeo app id>
      LUMEO_API_KEY: <your lumeo api key>
    privileged: true
    network_mode: host
    depends_on:
      - gpu
